# Generated by Django 5.2.11 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("porteria", "Porteria"),
                    ("recibidor", "Recibidor"),
                    ("inventario", "Inventario"),
                    ("despachador", "Despachador"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
