# Generated by Django 5.2.11 on 2026-02-22 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="contrasena",
                        max_length=128,
                        verbose_name="password",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        db_column="ultimo_ingreso",
                        null=True,
                        verbose_name="last login",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        db_column="es_superusuario",
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_column="correo", max_length=254, unique=True),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, db_column="nombres", max_length=150),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, db_column="apellidos", max_length=150),
                ),
                ("is_active", models.BooleanField(db_column="activo", default=True)),
                ("is_staff", models.BooleanField(db_column="es_personal", default=False)),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_column="fecha_registro",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        db_table="usuarios_grupos",
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        db_table="usuarios_permisos",
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "db_table": "usuarios",
            },
        ),
    ]
