# Generated by Django 5.2.11 on 2026-02-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacion",
                    models.CharField(
                        help_text="Identificación única del buque (IMO, nombre, etc.)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_arribo", models.DateTimeField()),
                ("procedencia", models.CharField(blank=True, max_length=200)),
                ("destino", models.CharField(blank=True, max_length=200)),
                ("cantidad_vehiculos", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Buque",
                "verbose_name_plural": "Buques",
                "db_table": "users_buque",
                "ordering": ["-fecha_arribo"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "permisos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de permisos asociados al rol",
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "users_role",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="users_user",
        ),
        migrations.CreateModel(
            name="Despacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cantidad_vehiculos", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En proceso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "buque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="despachos",
                        to="users.buque",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que realizó el despacho",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="despachos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Despacho",
                "verbose_name_plural": "Despachos",
                "db_table": "users_despacho",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ModeloVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("año", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("auto", "Automóvil"),
                            ("camioneta", "Camioneta"),
                            ("camion", "Camión"),
                            ("moto", "Motocicleta"),
                        ],
                        max_length=50,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Modelo de Vehículo",
                "verbose_name_plural": "Modelos de Vehículos",
                "db_table": "users_modelovehiculo",
                "unique_together": {("marca", "modelo", "año")},
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bin",
                    models.CharField(max_length=50, unique=True, verbose_name="BIN"),
                ),
                (
                    "qr_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Código QR"
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ingresado", "Ingresado"),
                            ("en_transito", "En tránsito"),
                            ("en_porteria", "En portería"),
                            ("en_inventario", "En inventario"),
                            ("despachado", "Despachado"),
                            ("recibido", "Recibido"),
                        ],
                        default="ingresado",
                        max_length=20,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "buque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehiculos",
                        to="users.buque",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehiculos",
                        to="users.modelovehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "users_vehiculo",
            },
        ),
        migrations.CreateModel(
            name="Recibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos_json",
                    models.JSONField(
                        default=dict,
                        help_text="Datos del recibo (destino, cliente, etc.)",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("recibido", "Recibido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "despacho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to="users.despacho",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to="users.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo",
                "verbose_name_plural": "Recibos",
                "db_table": "users_recibo",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoPorteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "persona",
                    models.CharField(
                        help_text="Persona responsable del movimiento", max_length=200
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_porteria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_porteria",
                        to="users.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Portería",
                "verbose_name_plural": "Movimientos Portería",
                "db_table": "users_movimientoporteria",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checklist_json",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con los ítems del checklist y su estado",
                    ),
                ),
                ("completo", models.BooleanField(default=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="users.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "db_table": "users_inventario",
            },
        ),
        migrations.CreateModel(
            name="Impronta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_url", models.URLField()),
                (
                    "datos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos técnicos de la impronta",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                            ("fallida", "Fallida"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improntas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impronta",
                        to="users.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impronta",
                "verbose_name_plural": "Improntas",
                "db_table": "users_impronta",
            },
        ),
        migrations.CreateModel(
            name="DespachoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden_escaneo",
                    models.IntegerField(
                        help_text="Orden en que se escaneó el vehículo"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "despacho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="users.despacho",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="despachos",
                        to="users.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo en Despacho",
                "verbose_name_plural": "Vehículos en Despacho",
                "db_table": "users_despachovehi",
            },
        ),
        migrations.AddIndex(
            model_name="vehiculo",
            index=models.Index(fields=["estado"], name="users_vehic_estado_54534d_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiculo",
            index=models.Index(fields=["buque"], name="users_vehic_buque_i_0aca4e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="despachovehiculo",
            unique_together={("despacho", "vehiculo")},
        ),
    ]
